blank_issues_enabled: false
contact_links:
  - name: General Question or Discussion
    url: https://github.com/prakhartripath0001/Enterprise-Learning-Management-System-LMS-with-DevOps-AI-Assistant/discussions
    about: Ask questions or discuss features with the community.
